<?php

/**
 * @file
 * @todo.
 */
        
//class zabbix_db_handler_field_templates extends views_handler_field {
//  
//  function init(&$view, &$options) {
//    parent::init($view, $options);
//    
//    $dbg = 1;
//    // Всегда добавляем hostID поля к запросам
//    //$this->additional_fields['templates'] = array('table' => 'hosts', 'field' => 'hostid');
//    
//  }  
//  /**
//   * Called to add the field to a query.
//   */
//  function query() {
//    $this->ensure_my_table();
//    $this->query->add_where(0, 'items.templateid = hosts.hostid');
////    // Add the field.
////    $params = $this->options['group_type'] != 'group' ? array('function' => $this->options['group_type']) : array();
////    $this->field_alias = $this->query->add_field($this->table_alias, $this->real_field, NULL, $params);
//
////    $this->add_additional_fields();
//  }
//  
//}



